env:
  - DATABASE_URL="dbname=ireporter host=localhost port=5432 user=elishamisoi password=postgres"
language: python
python:
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script: nosetests  app/tests

after_success:
  - coveralls